name: Build Docker image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-gh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image but dont push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false

  build-bs:
      runs-on: blacksmith-staging
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup buildx
          uses: useblacksmith/setup-buildx-action@v1
        - name: Build image but dont push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: false
