name: Javascript Lint and Test

on: pull_request

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 16
      - name: Install dev deps
        working-directory: src/dispatch/static/dispatch
        run: |
          npm install
      - name: Run ESLint
        working-directory: src/dispatch/static/dispatch
        run: |
          npm run lint
