name: "playwright"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

env:
  LOG_LEVEL: ERROR
  STATIC_DIR:
  DATABASE_HOSTNAME: localhost
  DATABASE_CREDENTIALS: dispatch:dispatch
  DISPATCH_ENCRYPTION_KEY: NJHDWDJ3PbHT8h
  DISPATCH_JWT_SECRET: foo

jobs:
  end-to-end:
    strategy:
      matrix:
        runner:
          [
            "blacksmith-2vcpu-ubuntu-2204",
            "blacksmith-4vcpu-ubuntu-2204",
            "blacksmith-8vcpu-ubuntu-2204",
            "blacksmith-16vcpu-ubuntu-2204",
            "ubuntu-latest",
          ]
    runs-on: ${{ matrix.runner }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: dispatch
          POSTGRES_PASSWORD: dispatch
          POSTGRES_DB: dispatch
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up Python 3.11 (Blacksmith)
        if: matrix.runner != 'ubuntu-latest'
        uses: useblacksmith/setup-python@v6
        with:
          python-version: 3.11
      - name: Set up Node.js
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Set up Node.js (Blacksmith)
        if: matrix.runner != 'ubuntu-latest'
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 16
      - name: Cache pip packages
        if: matrix.runner == 'ubuntu-latest'
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache pip packages (Blacksmith)
        if: matrix.runner != 'ubuntu-latest'
        uses: useblacksmith/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install python dependencies
        run: |
          export DISPATCH_LIGHT_BUILD=1
          python -m pip install --upgrade pip
          pip install psycopg[binary]
          pip install -e ".[dev]"
      - name: Install npm dependencies
        run: |
          npm ci -D --prefix src/dispatch/static/dispatch
          npm install -D @playwright/test
      - name: Install playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Setup sample database
        run: dispatch database restore --dump-file data/dispatch-sample-data.dump && dispatch database upgrade
      - name: Run tests
        run: npx playwright test --project=chromium
